# Generated by Django 5.0 on 2024-06-25 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc245c2c-0de8-4e8c-ae2f-aaa00b4ca89a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc245c2c-0de8-4e8c-ae2f-aaa00b4ca89a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
