# Generated by Django 5.0 on 2024-06-25 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_commentlike_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc245c2c-0de8-4e8c-ae2f-aaa00b4ca89a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc245c2c-0de8-4e8c-ae2f-aaa00b4ca89a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc245c2c-0de8-4e8c-ae2f-aaa00b4ca89a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc245c2c-0de8-4e8c-ae2f-aaa00b4ca89a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
